"""Closed configuration consumers; no registry entry grants execution or authority.

Module/class locators below are implementation-owned constants, never input values.
Consumer byte limits mirror their existing loaders; the exposed helper has a new
shape-check ceiling and the unsupported human template has no consuming limit.
Inputs are documentary inventory, not an installed-wheel checkout requirement.
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib import import_module

from empirical_lawhood.kernel.serialization import CanonicalRecord


@dataclass(frozen=True, slots=True)
class ConfigurationConsumer:
    consumer: str
    schema_id: str | None
    record_module: str | None
    record_name: str | None
    disposition: str
    maximum_bytes: int | None
    requires_canonical: bool
    command: str
    owner: str
    supplied_inputs: tuple[str, ...]

    @property
    def authoring_maximum_bytes(self) -> int | None:
        if self.maximum_bytes is None:
            return None
        return min(4 * self.maximum_bytes, 128 * 1024**2)

    @property
    def preparation_allowed(self) -> bool:
        return self.disposition == "editable"

    @property
    def loader(self) -> str:
        if self.consumer == "prepared-prior-census":
            return "adapters.composition.prepared_response.native_authoring._prior_census"
        if self.consumer == "finite-prior-census":
            return "adapters.composition.finite_response_law.native_input._census"
        if self.disposition == "helper":
            return "documentary helper; no runner loader"
        if self.requires_canonical:
            return "kernel.decoding.decode_canonical_bytes"
        return "api.codecs.load_registered_authoring"

    def record_type(self) -> type[CanonicalRecord]:
        if self.record_module is None or self.record_name is None:
            raise ValueError("this consumer has no canonical record constructor")
        record = getattr(import_module(self.record_module), self.record_name)
        if not isinstance(record, type) or not issubclass(record, CanonicalRecord):
            raise TypeError("configuration registry contains a non-record owner")
        if record.SCHEMA != self.schema_id:
            raise ValueError("configuration registry schema differs from its owner")
        return record


# Closed role dispositions for installed experiment and shared configuration inputs.
_CONSUMER_ROWS = (
 ('preparation-diagnostic-phase', 'empirical-lawhood/constructed-preparation-applicability/diagnostic-phase-input', 'empirical_lawhood.adapters.methods.constructed_preparation_applicability.diagnostic_records', 'PreparationDiagnosticPhaseInput', 'retained', 4194304, True, 'campaign preparation-diagnostic-phase-prepare', 'PreparationDiagnosticPhaseInput', ()),
 ('preparation-diagnostics', 'empirical-lawhood/constructed-preparation-applicability/diagnostic-input', 'empirical_lawhood.adapters.methods.constructed_preparation_applicability.diagnostic_records', 'PreparationDiagnosticInput', 'editable', 8388608, True, 'campaign preparation-diagnostics', 'PreparationDiagnosticInput', ()),
 ('matrix-geometry', 'empirical-lawhood/matrix-geometry/scan-input', 'empirical_lawhood.api.matrix_geometry', 'MatrixGeometryScanInput', 'editable', 8388608, True, 'campaign matrix-geometry-prove', 'MatrixGeometryScanInput', ('experiments/matrix-geometry/input.json',)),
 ('selected-parent', 'empirical-lawhood/selected-events/parent-request', 'empirical_lawhood.api.selected_events', 'MatrixSelectedParentRequest', 'editable', 1048576, True, 'campaign selected-parent-reconstruct', 'MatrixSelectedParentRequest', ('experiments/selected-events/parent.json',)),
 ('selected-events', 'empirical-lawhood/selected-events/input', 'empirical_lawhood.api.selected_events', 'MatrixSelectedEventInput', 'editable', 16777216, True, 'campaign selected-events-run', 'MatrixSelectedEventInput', ()),
 ('matrix-history-allocation', 'empirical-lawhood/matrix-history-analysis/allocation', 'empirical_lawhood.adapters.methods.matrix_history_analysis.records', 'MatrixHistoryAllocation', 'editable', 1048576, True, 'campaign matrix-history-allocation', 'MatrixHistoryAllocation', ('experiments/matrix-history-analysis/allocation.json',)),
 ('matrix-history-source', 'empirical-lawhood/matrix-history-analysis/source-config', 'empirical_lawhood.adapters.methods.matrix_history_analysis.records', 'MatrixHistorySourceConfig', 'editable', 1048576, True, 'campaign matrix-history-source-export', 'MatrixHistorySourceConfig', ('experiments/matrix-history-analysis/source.json',)),
 ('matrix-history-analysis', 'empirical-lawhood/matrix-history-analysis/analysis-config', 'empirical_lawhood.adapters.methods.matrix_history_analysis.records', 'MatrixHistoryAnalysisConfig', 'editable', 1048576, True, 'campaign matrix-history-analyze', 'MatrixHistoryAnalysisConfig', ('experiments/matrix-history-analysis/algebra.json', 'experiments/matrix-history-analysis/passive.json')),
 ('matrix-transient-analysis', 'empirical-lawhood/methods/matrix-preparation-analysis/transient-analysis-config', 'empirical_lawhood.adapters.methods.matrix_preparation_analysis.records', 'TransientAnalysisConfig', 'editable', 65536, True, 'campaign matrix-transient-analyze', 'TransientAnalysisConfig', ('experiments/matrix-transient/input.json',)),
 ('matrix-baseline-analysis', 'empirical-lawhood/methods/matrix-preparation-analysis/baseline-support-config', 'empirical_lawhood.adapters.methods.matrix_preparation_analysis.records', 'BaselineSupportConfig', 'editable', 65536, True, 'campaign matrix-baseline-analyze', 'BaselineSupportConfig', ('experiments/matrix-transient/baseline.json',)),
 ('matrix-tangent', 'empirical-lawhood/methods/matrix-preparation-analysis/tangent-preparation-config', 'empirical_lawhood.adapters.methods.matrix_preparation_analysis.tangent_records', 'TangentPreparationConfig', 'editable', 4194304, True, 'campaign matrix-tangent-source-export', 'TangentPreparationConfig', ('experiments/matrix-tangent/input.json',)),
('preparation-retained-result', 'empirical-lawhood/preparation-applicability/retained-result', 'empirical_lawhood.adapters.methods.preparation_applicability.result_access', 'PreparationApplicabilityRetainedResult', 'retained', 16777216, True, 'campaign preparation-result', 'PreparationApplicabilityRetainedResult', ()),
 ('preparation-native-conformance', 'empirical-lawhood/preparation-applicability/native-conformance', 'empirical_lawhood.adapters.methods.preparation_applicability.conformance', 'PreparationApplicabilityNativeConformance', 'retained', 1048576, True, 'campaign preparation-conformance', 'PreparationApplicabilityNativeConformance', ()),
 ('preparation-exposure-inspection', 'empirical-lawhood/preparation-applicability/exposure-inspection', 'empirical_lawhood.adapters.methods.preparation_applicability.issued_inputs', 'PreparationApplicabilityExposureInspection', 'retained', 4194304, True, 'campaign preparation-exposure-inspect', 'PreparationApplicabilityExposureInspection', ()),
 ('preparation-published-input', 'empirical-lawhood/preparation-applicability/published-input', 'empirical_lawhood.adapters.methods.preparation_applicability.issued_inputs', 'PreparationApplicabilityPublishedInput', 'retained', 16777216, True, 'campaign preparation-input-publish', 'PreparationApplicabilityPublishedInput', ()),
 ('preparation-panel-publication', 'empirical-lawhood/preparation-applicability/panel-publication', 'empirical_lawhood.adapters.methods.preparation_applicability.panel_inputs', 'PreparationApplicabilityPanelPublication', 'retained', 16777216, True, 'campaign preparation-panel-bind', 'PreparationApplicabilityPanelPublication', ()),
 ('finite-current-result', 'empirical-lawhood/composition/finite-response-law/current-result-input', 'empirical_lawhood.adapters.composition.finite_response_law.rerun_input', 'FiniteResponseLawCurrentResultInput', 'retained', 8388608, True, 'campaign finite-response-result', 'FiniteResponseLawCurrentResultInput', ()),
 ('rc-challenge-result', 'empirical-lawhood/simulator-morphism-challenges/retained-result', 'empirical_lawhood.adapters.simulator_morphism_challenges.retained_results', 'RCChallengeRetainedResult', 'retained', 16777216, True, 'campaign rc-challenge-result', 'RCChallengeRetainedResult', ()),
 ('rc-challenge-result-authority', 'empirical-lawhood/simulator-morphism-challenges/result-authority-context', 'empirical_lawhood.adapters.simulator_morphism_challenges.retained_results', 'RCChallengeResultAuthorityContext', 'retained', 1048576, True, 'campaign rc-challenge-result', 'RCChallengeResultAuthorityContext', ()),
 ('original-f', 'empirical-lawhood/methods/finite-response-law/original-finite-response-law', 'empirical_lawhood.adapters.methods.finite_response_law.original_f', 'OriginalFiniteResponseLaw', 'retained', 1048576, True, 'campaign original-f-check', 'OriginalFiniteResponseLaw', ()),
 ('current-nomination', 'empirical-lawhood/methods/finite-response-law/current-nomination-operand', 'empirical_lawhood.adapters.methods.finite_response_law.nominated_package', 'CurrentNominationOperand', 'retained', 1048576, True, 'campaign nomination-check', 'CurrentNominationOperand', ()),
 ('saved-matrix-arrays', 'empirical-lawhood/kernel/saved-matrix-arrays', 'empirical_lawhood.kernel.matrix_inputs', 'SavedMatrixArrays', 'retained', 4194304, True, 'campaign preparation-operands-export', 'SavedMatrixArrays', ()),
 ('preparation-source', 'empirical-lawhood/methods/finite-response-law/current-preparation-source-config', 'empirical_lawhood.adapters.methods.finite_response_law.transient_bridge_source_records', 'CurrentPreparationSourceConfig', 'editable', 65536, True, 'campaign preparation-source-export', 'CurrentPreparationSourceConfig', ('experiments/matrix-inputs/preparation-source.json',)),
 ('matrix-source', 'empirical-lawhood/methods/finite-response-law/matrix-preparation-source-config', 'empirical_lawhood.adapters.methods.finite_response_law.transient_bridge_source_records', 'MatrixPreparationSourceConfig', 'editable', 65536, True, 'campaign matrix-source-export', 'MatrixPreparationSourceConfig', ('experiments/matrix-inputs/matrix-source.json',)),
 ('rc-challenge-source', 'empirical-lawhood/simulator-morphism-challenges/source-export-config', 'empirical_lawhood.adapters.simulator_morphism_challenges.numeric_inputs', 'RCChallengeSourceExportConfig', 'editable', 1048576, True, 'campaign rc-challenge-source-export', 'RCChallengeSourceExportConfig', ('experiments/rc-challenges/source-export.json',)),
 ('rc-challenge-phase', 'empirical-lawhood/simulator-morphism-challenges/simulator-morphism-challenge-config', 'empirical_lawhood.adapters.simulator_morphism_challenges.contracts', 'SimulatorMorphismChallengeConfig', 'editable', 65536, True, 'campaign rc-challenge-author', 'SimulatorMorphismChallengeConfig', ('experiments/rc-challenges/canary.json', 'experiments/rc-challenges/nomination.json', 'experiments/rc-challenges/development.json', 'experiments/rc-challenges/evaluation.json')),
 ('finite-rerun', 'empirical-lawhood/composition/finite-response-law/rerun-input', 'empirical_lawhood.adapters.composition.finite_response_law.rerun_input', 'FiniteResponseLawRerunInput', 'editable', 4194304, True, 'campaign finite-response-author', 'FiniteResponseLawRerunInput', ('experiments/finite-response-law/rerun-calibration.json',)),
 ('finite-current-allocation', 'empirical-lawhood/composition/finite-response-law/current-allocation', 'empirical_lawhood.adapters.composition.finite_response_law.rerun_input', 'FiniteResponseLawCurrentAllocation', 'editable', 1048576, True, 'campaign finite-response-author', 'FiniteResponseLawCurrentAllocation', ('experiments/finite-response-law/current-calibration-allocation.json', 'experiments/finite-response-law/current-evaluation-allocation.json')),
 ('finite-current-exposure', 'empirical-lawhood/composition/finite-response-law/current-exposure', 'empirical_lawhood.adapters.composition.finite_response_law.rerun_input', 'FiniteResponseLawCurrentExposure', 'retained', 4194304, True, 'campaign finite-response-author', 'FiniteResponseLawCurrentExposure', ('experiments/finite-response-law/current-exposure.json',)),
 ('finite-current-parent', 'empirical-lawhood/composition/finite-response-law/current-parent', 'empirical_lawhood.adapters.composition.finite_response_law.rerun_input', 'FiniteResponseLawCurrentParent', 'retained', 8388608, True, 'campaign finite-response-author', 'FiniteResponseLawCurrentParent', ()),
 ('finite-runtime-context', 'empirical-lawhood/composition/finite-response-law/finite-response-law-runtime-context', 'empirical_lawhood.adapters.composition.finite_response_law.consumer_ports', 'FiniteResponseLawRuntimeContext', 'editable', 1048576, True, 'campaign finite-response-bind-runtime', 'FiniteResponseLawRuntimeContext', ()),
 ('preparation-applicability-selection', 'empirical-lawhood/composition/preparation-applicability/selection', 'empirical_lawhood.adapters.composition.preparation_applicability.selection', 'PreparationApplicabilitySelection', 'editable', 4194304, True, 'campaign preparation-author', 'PreparationApplicabilitySelection', ()),
 ('preparation-applicability-stage', 'empirical-lawhood/preparation-applicability/stage', 'empirical_lawhood.adapters.methods.preparation_applicability.config', 'PreparationApplicabilityStage', 'editable', 4194304, True, 'campaign preparation-author', 'PreparationApplicabilityStage', ()),
 ('preparation-applicability-source', 'empirical-lawhood/preparation-applicability/source', 'empirical_lawhood.adapters.methods.preparation_applicability.config', 'PreparationApplicabilitySource', 'editable', 1048576, True, 'campaign preparation-author', 'PreparationApplicabilitySource', ()),
 ('constructed-preparation-applicability-selection', 'empirical-lawhood/composition/constructed-preparation-applicability/selection', 'empirical_lawhood.adapters.composition.constructed_preparation_applicability.selection', 'ConstructedPreparationApplicabilitySelection', 'editable', 4194304, True, 'campaign preparation-author', 'ConstructedPreparationApplicabilitySelection', ()),
 ('constructed-preparation-applicability-stage', 'empirical-lawhood/constructed-preparation-applicability/stage', 'empirical_lawhood.adapters.methods.constructed_preparation_applicability.config', 'ConstructedPreparationStage', 'editable', 4194304, True, 'campaign preparation-author', 'ConstructedPreparationStage', ()),
 ('constructed-preparation-applicability-source', 'empirical-lawhood/constructed-preparation-applicability/source', 'empirical_lawhood.adapters.methods.constructed_preparation_applicability.config', 'ConstructedPreparationSource', 'editable', 1048576, True, 'campaign preparation-author', 'ConstructedPreparationSource', ()),
 ('rc-information',
  'empirical-lawhood/methods/rc-information/config',
  'empirical_lawhood.adapters.methods.rc_information.contracts',
  'RCInformationConfig',
  'editable',
  65536,
  True,
  'example rc-information',
  'RCInformationConfig',
  ('experiments/rc-information/input.json',)),
 ('matrix-allocation',
  'empirical-lawhood/kernel/matrix-allocation',
  'empirical_lawhood.kernel.matrix_inputs',
  'MatrixAllocation',
  'editable',
  1048576,
  True,
  'campaign preparation-operands-export',
  'MatrixAllocation',
  ('experiments/matrix-inputs/allocation.json', 'experiments/preparation-applicability/conformance-allocation.json')),
 ('rc-ladder-model',
  'empirical-lawhood/adapters/simulators/rc-ladder-response/resistor-capacitor-ladder-model-config',
  'empirical_lawhood.adapters.simulators.rc_ladder_response.contracts',
  'ResistorCapacitorLadderModelConfig',
  'editable',
  65536,
  True,
  'campaign rc-ladder-native-check',
  'ResistorCapacitorLadderModelConfig',
  ('experiments/rc-ladder-response/model.json',)),
 ('finite-calibration-input',
  'empirical-lawhood/composition/finite-response-law/finite-response-law-calibration-input',
  'empirical_lawhood.adapters.composition.finite_response_law.native_input',
  'FiniteResponseLawCalibrationInput',
  'editable',
  16384,
  False,
  'campaign finite-response-input-check',
  'FiniteResponseLawCalibrationInput',
  ('experiments/finite-response-law/finite-calibration-input.json',)),
 ('finite-stage-input',
  'empirical-lawhood/composition/finite-response-law/finite-response-law-stage-input',
  'empirical_lawhood.adapters.composition.finite_response_law.stage_input',
  'FiniteResponseLawStageInput',
  'editable',
  16384,
  False,
  'campaign finite-response-stage-input-check',
  'FiniteResponseLawStageInput',
  ('experiments/finite-response-law/calibration-input.json',
   'experiments/finite-response-law/calibration-stage-input.json',
   'experiments/finite-response-law/informative-composition-input.json',
   'experiments/finite-response-law/preparation-screen-input.json',
   'experiments/finite-response-law/prospective-continuation-input.json',
   'experiments/finite-response-law/prospective-evaluation-input.json',
   'experiments/finite-response-law/supplemental-development-input.json')),
 ('prepared-prior-census',
  'empirical-lawhood/composition/prepared-response/prepared-exposure-inspection',
  None,
  None,
  'import',
  67108864,
  False,
  'campaign matrix-response-author --prior-inspection',
  '_prior_census',
  ('experiments/reactor-response/exposed-inputs/prepared-response-prior-exposure.json',)),
 ('prepared-dependent-input',
  'empirical-lawhood/composition/prepared-response/prepared-response-dependent-input',
  'empirical_lawhood.adapters.composition.prepared_response.dependent_input',
  'PreparedResponseDependentInput',
  'editable',
  16384,
  False,
  'campaign dependent-response-input-check',
  'PreparedResponseDependentInput',
  ('experiments/prepared-response/prepared-dependent-refinement-input.json',
   'experiments/prepared-response/prepared-fresh-response-calibration-input.json')),
 ('matrix-response-authoring',
  'empirical-lawhood/composition/prepared-response/prepared-response-native-authoring-input',
  'empirical_lawhood.adapters.composition.prepared_response.native_authoring',
  'PreparedResponseNativeAuthoringInput',
  'editable',
  1048576,
  False,
  'campaign matrix-response-author',
  'PreparedResponseNativeAuthoringInput',
  ('experiments/causal-response/causal-author.json',
   'experiments/information-response/information-author.json',
   'experiments/prepared-response/prepared-source-qualification-author.json')),
 ('reactor-assigned-profile',
  'empirical-lawhood/composition/reactor-prefix-response/assigned-reactor-authoring-profile',
  'empirical_lawhood.adapters.composition.reactor_prefix_response.fresh_authoring',
  'AssignedReactorAuthoringProfile',
  'retained',
  67108864,
  True,
  'campaign reactor-author',
  'AssignedReactorAuthoringProfile',
  ('experiments/reactor-response/exposed-inputs/reactor-assigned-exposed.json',)),
 ('reactor-fresh-profile',
  'empirical-lawhood/composition/reactor-prefix-response/fresh-reactor-authoring-profile',
  'empirical_lawhood.adapters.composition.reactor_prefix_response.fresh_authoring',
  'FreshReactorAuthoringProfile',
  'editable',
  67108864,
  True,
  'campaign reactor-author',
  'FreshReactorAuthoringProfile',
  ('experiments/reactor-response/profile.json',)),
 ('response-composition-input',
  'empirical-lawhood/composition/response-composition/response-composition-input',
  'empirical_lawhood.adapters.composition.response_composition.input',
  'ResponseCompositionInput',
  'editable',
  16384,
  False,
  'campaign response-composition-input-check',
  'ResponseCompositionInput',
  ('experiments/causal-transfer-audit/analysis-input.json',)),
 ('exposed-inventory',
  'empirical-lawhood/examples/exposed-inventory',
  None,
  None,
  'helper',
  65536,
  False,
  'scripts/generate_operator_examples.py',
  'documentary helper',
  ('experiments/reactor-response/exposed-inputs/exposed-inventory.json',)),
 ('finite-prior-census',
  'empirical-lawhood/methods/finite-response-law/native-exposure-metadata',
  None,
  None,
  'import',
  134217728,
  False,
  'campaign finite-response-stage-input-check --prior-exposure',
  '_census',
  ('experiments/reactor-response/exposed-inputs/finite-response-prior-exposure.json',)),
 ('propulsion-reference',
  'empirical-lawhood/methods/synthetic-propulsion-development-input',
  'empirical_lawhood.adapters.methods.synthetic_propulsion_development_input',
  'SyntheticPropulsionDevelopmentInput',
  'editable',
  16384,
  False,
  'campaign propulsion-reference-check',
  'SyntheticPropulsionDevelopmentInput',
  ('experiments/propulsion-reliability-reference/config.json',)),
 ('glenn-import-selection',
  'empirical-lawhood/physical/glenn/glenn-input-quickstart',
  'empirical_lawhood.adapters.physical.glenn.quickstart',
  'GlennInputQuickstart',
  'editable',
  16384,
  False,
  'campaign glenn-import-check',
  'GlennInputQuickstart',
  ('experiments/laser-archive-inspection/config.json',)),
 ('fair-mast-selection',
  'empirical-lawhood/physical/mast-archive/fair-mast-public-selection',
  'empirical_lawhood.adapters.physical.mast_archive.fresh_source',
  'FairMastPublicSelection',
  'editable',
  65536,
  True,
  'source acquire',
  'FairMastPublicSelection',
  ('configs/sources/fair-mast-level2.json',)),
 ('reaction-development',
  'empirical-lawhood/reaction-diffusion-development/reaction-diffusion-development-input',
  'empirical_lawhood.adapters.simulators.reaction_diffusion_development_input',
  'ReactionDiffusionDevelopmentInput',
  'editable',
  32768,
  False,
  'campaign reaction-response-native-check',
  'ReactionDiffusionDevelopmentInput',
  ('experiments/reaction-diffusion-response/config.json', 'experiments/reactor-flow-response/config.json')),
 ('scale-morphism-reference',
  'empirical-lawhood/reference-worlds/physical-scale-morphism/physical-scale-morphism-truth-suite-config',
  'empirical_lawhood.adapters.reference_worlds.physical_scale_morphism.contracts',
  'PhysicalScaleMorphismTruthSuiteConfig',
  'editable',
  16384,
  False,
  'campaign scale-morphism-reference-check',
  'PhysicalScaleMorphismTruthSuiteConfig',
  ('experiments/response-method-reference/config.json',)),
 ('operator-storage',
  'empirical-lawhood/runtime/operator-storage-profile',
  'empirical_lawhood.runtime.operator_profile',
  'OperatorStorageProfile',
  'editable',
  134217728,
  False,
  'doctor',
  'OperatorStorageProfile',
  ('configs/operator-storage.example.json',)),
 ('material-control-input',
  'empirical-lawhood/simulators/ambient-pressure-superconductor/material-control-input-preflight',
  'empirical_lawhood.adapters.simulators.ambient_pressure_superconductor.material_control_input_preflight',
  'MaterialControlInputPreflight',
  'editable',
  32768,
  False,
  'campaign material-workflow-input-check',
  'MaterialControlInputPreflight',
  ('experiments/material-control-inputs/control-inputs.json',)),
 ('lattice-method-authoring',
  'empirical-lawhood/simulators/ambient-pressure-superconductor/synthetic-material-response-method-config',
  'empirical_lawhood.adapters.simulators.ambient_pressure_superconductor.synthetic_material_method_contracts',
  'SyntheticMaterialResponseMethodConfig',
  'editable',
  131072,
  True,
  'campaign synthetic-material-author',
  'SyntheticMaterialResponseMethodConfig',
  ('experiments/lattice-pairing-method/authoring.json',)),
 ('brian2-current',
  'empirical-lawhood/simulators/brian2-neuron-current-response/brian2-lif-native-config',
  'empirical_lawhood.adapters.simulators.brian2_neuron_current_response.contracts',
  'Brian2LIFNativeConfig',
  'editable',
  16384,
  True,
  'campaign brian2-native-check',
  'Brian2LIFNativeConfig',
  ('experiments/neuron-current-response/config.json',)),
 ('finite-canary',
  'empirical-lawhood/simulators/finite-response-law/finite-response-law-canary',
  'empirical_lawhood.adapters.simulators.finite_response_law.native_quickstart',
  'FiniteResponseLawCanary',
  'editable',
  16384,
  False,
  'campaign finite-response-native-check',
  'FiniteResponseLawCanary',
  ('experiments/finite-response-law/finite-canary.json',)),
 ('grid-development',
  'empirical-lawhood/simulators/grid2op-response/grid2-op-development-input',
  'empirical_lawhood.adapters.simulators.grid2op_response.native_quickstart',
  'Grid2OpDevelopmentInput',
  'editable',
  16384,
  False,
  'campaign grid2op-native-check',
  'Grid2OpDevelopmentInput',
  ('experiments/grid-response-inputs/config.json',)),
 ('tokamak-control',
  'empirical-lawhood/simulators/gym-torax-native/gym-torax-native-quickstart',
  'empirical_lawhood.adapters.simulators.gym_torax_native.native_quickstart',
  'GymToraxNativeQuickstart',
  'editable',
  16384,
  False,
  'campaign gym-torax-native-check',
  'GymToraxNativeQuickstart',
  ('experiments/tokamak-control-response/config.json',)),
 ('prepared-canary',
  'empirical-lawhood/simulators/prepared-response/prepared-response-prepared-canary',
  'empirical_lawhood.adapters.simulators.prepared_response.native_quickstart',
  'PreparedResponsePreparedCanary',
  'editable',
  16384,
  False,
  'campaign prepared-response-native-check',
  'PreparedResponsePreparedCanary',
  ('experiments/prepared-response/prepared-canary.json',)),
 ('battery-development',
  'empirical-lawhood/simulators/py-ba-mm-development-input',
  'empirical_lawhood.adapters.simulators.pybamm_development_input',
  'PyBaMMDevelopmentInput',
  'editable',
  16384,
  False,
  'campaign battery-native-check',
  'PyBaMMDevelopmentInput',
  ('experiments/battery-response-and-restart/config.json',)),
 ('rc-ladder-study',
  'empirical-lawhood/simulators/rc-ladder-response/resistor-capacitor-ladder-study-config',
  'empirical_lawhood.adapters.simulators.rc_ladder_response.contracts',
  'ResistorCapacitorLadderStudyConfig',
  'editable',
  131072,
  True,
  'campaign circuit-author',
  'ResistorCapacitorLadderStudyConfig',
  ('experiments/rc-ladder-response/study.json',)),
 ('reactor-batch-input',
  'empirical-lawhood/simulators/reactor-prefix-response/reactor-batch-input',
  'empirical_lawhood.adapters.simulators.reactor_prefix_response.batch_input',
  'ReactorBatchInput',
  'editable',
  16384,
  False,
  'campaign reactor-batch-input-check',
  'ReactorBatchInput',
  ('experiments/reactor-response/batch-input.json',)),
 ('reactor-prepared-input',
  'empirical-lawhood/simulators/reactor-prefix-response/reactor-prepared-input',
  'empirical_lawhood.adapters.simulators.reactor_prefix_response.prepared_input',
  'ReactorPreparedInput',
  'editable',
  16384,
  False,
  'campaign reactor-prepared-input-check',
  'ReactorPreparedInput',
  ('experiments/reactor-response/causal-response-study-input.json',
   'experiments/reactor-response/feed-input.json',
   'experiments/reactor-response/finite-control-frontier-input.json',
   'experiments/reactor-response/local-input.json',
   'experiments/reactor-response/matched-replay-history-input.json',
   'experiments/reactor-response/regime-input.json',
   'experiments/reactor-response/selected-action-response-input.json',
   'experiments/reactor-response/staged-pulse-response-input.json')),
 ('tokamak-heat',
  'empirical-lawhood/simulators/torax-native/native-torax-quickstart',
  'empirical_lawhood.adapters.simulators.torax_native.native_quickstart',
  'NativeToraxQuickstart',
  'editable',
  32768,
  False,
  'campaign torax-native-check',
  'NativeToraxQuickstart',
  ('experiments/tokamak-heat-response/config.json',)),
 ('electron-gas-reference',
  'empirical-lawhood/simulators/uniform-electron-gas-response/analytic-reference-config',
  'empirical_lawhood.adapters.simulators.uniform_electron_gas_response.native_quickstart',
  'UniformElectronGasAnalyticReferenceConfig',
  'editable',
  32768,
  True,
  'campaign electron-gas-reference-check',
  'UniformElectronGasAnalyticReferenceConfig',
  ('experiments/electron-gas-response/config.json',)),
 ('evidence-provenance-template',
  None,
  None,
  None,
  'helper',
  None,
  False,
  'manual evidence provenance',
  'human-edited template',
  ('configs/templates/evidence-provenance.yaml',)))

CONSUMERS = tuple(ConfigurationConsumer(*row) for row in _CONSUMER_ROWS)


def consumers_for_schema(schema_id: str) -> tuple[ConfigurationConsumer, ...]:
    return tuple(item for item in CONSUMERS if item.schema_id == schema_id)


def consumer_by_id(consumer: str) -> ConfigurationConsumer:
    for item in CONSUMERS:
        if item.consumer == consumer:
            return item
    raise ValueError(f"unknown configuration consumer: {consumer}")
