"""Closed availability decisions for parameterised simulator providers."""

from __future__ import annotations


PYBAMM_PARAMETERISED_PROVIDER_DECISION = "PYBAMM_PARAMETERISED_PROVIDER_ABSENT"
PYBAMM_PARAMETERISED_MISSING_PORTS = (
    "BOUNDED_NATIVE_EPISODE_SCHEMA",
    "ISSUED_PARAMETERISED_SOURCE_VIEW_CONFIG",
    "NATIVE_TO_SELECTED_PROJECTION_TRANSLATION",
    "OPEN_SUBSTRATE_BINDING",
    "V4_CAMPAIGN_RUNTIME_PROVIDER",
    "V4_CAPABILITY_MANIFEST",
    "V4_TASK_RUNNER",
)


__all__ = [
    "PYBAMM_PARAMETERISED_MISSING_PORTS",
    "PYBAMM_PARAMETERISED_PROVIDER_DECISION",
]
