"""Orthogonal operational and scientific status axes."""

from __future__ import annotations

from enum import StrEnum


class OperationalStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"
    INVALIDATED = "INVALIDATED"


class ReadinessStatus(StrEnum):
    READY = "READY"
    REQUIRES_PROTOCOL_FREEZE = "REQUIRES_PROTOCOL_FREEZE"
    REQUIRES_NEW_DATA = "REQUIRES_NEW_DATA"
    PREREQUISITE_NOT_MET = "PREREQUISITE_NOT_MET"
    SOURCE_PREREQUISITE_NOT_MET = "SOURCE_PREREQUISITE_NOT_MET"
    AUTHORITY_REQUIRED = "AUTHORITY_REQUIRED"
    COMPUTABILITY_BOUNDARY = "COMPUTABILITY_BOUNDARY"


class ScientificStatus(StrEnum):
    NOT_TESTED = "NOT_TESTED"
    SUPPORTED = "SUPPORTED"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    MIXED = "MIXED"
    PARTIAL = "PARTIAL"
    UNEVALUABLE = "UNEVALUABLE"


class AdmissionStatus(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    ADMITTED = "ADMITTED"
    EMPTY = "EMPTY"
    PARTIAL = "PARTIAL"
    UNEVALUABLE = "UNEVALUABLE"


class ControllerValidationStatus(StrEnum):
    NOT_TESTED = "NOT_TESTED"
    SYNTHESIZED = "SYNTHESIZED"
    CONFORMANCE_TESTED = "CONFORMANCE_TESTED"
    SIMULATION_VALIDATED = "SIMULATION_VALIDATED"
    ROBUST_SIMULATION_VALIDATED = "ROBUST_SIMULATION_VALIDATED"
    SHADOW_VALIDATED = "SHADOW_VALIDATED"
    HIL_VALIDATED = "HIL_VALIDATED"
    PROSPECTIVELY_TESTED = "PROSPECTIVELY_TESTED"


class LifecycleStatus(StrEnum):
    ACTIVE = "ACTIVE"
    TERMINAL = "TERMINAL"
    SUPERSEDED = "SUPERSEDED"
    INVALIDATED = "INVALIDATED"
