"""Generate the explicit static backbone-extension aggregate module."""

from __future__ import annotations

import argparse
import importlib
from pathlib import Path
from typing import Sequence

from empirical_lawhood.runtime.extension_bundles import ExtensionBundleContribution, compose_extension_bundle_aggregate


try:
    from ._descriptor_discovery import (
        discover_descriptors as _discover_descriptors,
        module_name,
        require_safe_output,
    )
except ImportError:  # Explicit script invocation outside the checkout.
    from _descriptor_discovery import (
        discover_descriptors as _discover_descriptors,
        module_name,
        require_safe_output,
    )


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = REPOSITORY_ROOT / "src/empirical_lawhood"
ALLOWLISTED_ROOTS = (
    PACKAGE_ROOT / "adapters/control",
    PACKAGE_ROOT / "adapters/methods",
    PACKAGE_ROOT / "adapters/physical",
    PACKAGE_ROOT / "adapters/simulators",
)
OUTPUT = PACKAGE_ROOT / "adapters/composition/generated_extension_bundles.py"
DESCRIPTOR_NAME = "extension_bundle.py"
SYMBOL_NAME = "EXTENSION_BUNDLE_CONTRIBUTION"


def _module_name(path: Path) -> str:
    return module_name(path, package_root=PACKAGE_ROOT)


def discover_descriptors() -> tuple[Path, ...]:
    return _discover_descriptors(
        package_root=PACKAGE_ROOT,
        roots=ALLOWLISTED_ROOTS,
        name=DESCRIPTOR_NAME,
        kind="extension",
    )


def load_contributions(
    paths: tuple[Path, ...],
) -> tuple[ExtensionBundleContribution, ...]:
    contributions = []
    for path in paths:
        module = importlib.import_module(_module_name(path))
        contribution = getattr(module, SYMBOL_NAME, None)
        if not isinstance(contribution, ExtensionBundleContribution):
            raise ValueError(f"extension descriptor omits {SYMBOL_NAME}: {path}")
        contributions.append(contribution)
    ordered = tuple(sorted(contributions, key=lambda value: value.contribution_id))
    compose_extension_bundle_aggregate(ordered)
    return ordered


def render_generated_module(paths: tuple[Path, ...]) -> str:
    contributions = load_contributions(paths)
    modules = tuple(_module_name(path) for path in paths)
    alias_by_id = {
        contribution.contribution_id: f"_contribution_{index:03d}"
        for index, contribution in enumerate(contributions)
    }
    module_by_id = {
        getattr(importlib.import_module(module), SYMBOL_NAME).contribution_id: module
        for module in modules
    }
    imports = [
        (
            f"from {module_by_id[contribution.contribution_id]} import (\n"
            f"    {SYMBOL_NAME} as {alias_by_id[contribution.contribution_id]},\n"
            ")"
        )
        for contribution in contributions
    ]
    aggregate = compose_extension_bundle_aggregate(contributions)
    aliases = ",\n    ".join(
        alias_by_id[contribution.contribution_id] for contribution in contributions
    )
    return "\n".join(
        (
            '"""Generated by scripts/generate_extension_bundle_aggregate.py; do not edit."""',
            "",
            "from empirical_lawhood.runtime.extension_bundles import (",
            "    compose_extension_bundle_aggregate,",
            ")",
            *imports,
            "",
            "EXTENSION_BUNDLE_CONTRIBUTIONS = (",
            f"    {aliases},",
            ")",
            "",
            "GENERATED_EXTENSION_BUNDLE_AGGREGATE = compose_extension_bundle_aggregate(",
            "    EXTENSION_BUNDLE_CONTRIBUTIONS",
            ")",
            f'EXPECTED_AGGREGATE_FINGERPRINT = "{aggregate.fingerprint()}"',
            "if GENERATED_EXTENSION_BUNDLE_AGGREGATE.fingerprint() != EXPECTED_AGGREGATE_FINGERPRINT:",
            '    raise RuntimeError("generated extension aggregate fingerprint drifted")',
            "",
            "__all__ = [",
            '    "EXPECTED_AGGREGATE_FINGERPRINT",',
            '    "EXTENSION_BUNDLE_CONTRIBUTIONS",',
            '    "GENERATED_EXTENSION_BUNDLE_AGGREGATE",',
            "]",
            "",
        )
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated output drifts")
    arguments = parser.parse_args(argv)
    expected = render_generated_module(discover_descriptors()).encode("utf-8")
    require_safe_output(OUTPUT, package_root=PACKAGE_ROOT)
    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_bytes() != expected:
            raise SystemExit("generated extension bundle aggregate is missing or stale")
        return 0
    OUTPUT.write_bytes(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
