"""Declarative lifecycle/effect metadata for generated CLI documentation."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CommandMetadata:
    command: str
    lifecycle: str
    evidence_role: str
    effects: str
    external_disk: str
    clean_commit: str
    authority: str
    documentation: str
    native_software: str | None = None
    native_status: str | None = None


GROUP_METADATA = (
    CommandMetadata("workflow", "installed", "static researcher task discovery", "read-only", "no", "no", "no", "experiments/README.md"),
    CommandMetadata("config", "installed", "consumer-specific editable input tooling", "validation/schema are read-only; preparation writes one explicitly new file", "no", "no", "no", "docs/configuration.md"),
    CommandMetadata(
        "example",
        "installed demonstration",
        "unqualified native prefix",
        "writes only the requested output directory",
        "no",
        "no",
        "no",
        "experiments/reactor-response/guide.md",
    ),
    CommandMetadata(
        "doctor",
        "installed",
        "diagnostic-only",
        "read-only",
        "inspected",
        "no",
        "no",
        "docs/cli.md",
    ),
    CommandMetadata(
        "system",
        "installed",
        "authoring/catalog",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
    ),
    CommandMetadata(
        "campaign",
        "installed",
        "protocol/execution",
        "mixed",
        "authority reads for executable packages. Run/resume writes",
        "run/resume",
        "bound authorization",
        "docs/cli.md",
    ),
    CommandMetadata(
        "capability",
        "installed",
        "static capability discovery",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
    ),
    CommandMetadata(
        "catalog",
        "installed",
        "metadata projection",
        "mixed",
        "projection input only",
        "no",
        "no",
        "docs/cli.md",
    ),
    CommandMetadata(
        "dataset",
        "installed",
        "dataset authoring/catalog",
        "mixed",
        "registered source/receipt scopes for authorized rebuild",
        "dataset rebuild",
        "dedicated durable operation authority",
        "docs/cli.md",
    ),
    CommandMetadata(
        "db",
        "installed",
        "local projection lifecycle",
        "mixed",
        "no",
        "no",
        "no",
        "docs/cli.md",
    ),
    CommandMetadata(
        "authority",
        "installed",
        "policy/preview metadata",
        "read-only",
        "no",
        "no",
        "outcome-blind",
        "docs/cli.md",
    ),
    CommandMetadata(
        "law",
        "installed",
        "response-law metadata",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
    ),
    CommandMetadata(
        "atlas",
        "installed",
        "atlas metadata/gaps",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
    ),
    CommandMetadata(
        "admission",
        "installed",
        "admission metadata",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
    ),
    CommandMetadata(
        "control",
        "installed",
        "controller metadata/reference conformance",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
    ),
    CommandMetadata(
        "source",
        "installed",
        "public source preparation",
        "preview is read-only. Acquire and recovery write guarded custody",
        "selected public source and explicit external profile",
        "acquire and recovery",
        "separate typed source-acquisition and custody-publication authority",
        "docs/sources.md",
    ),
)


RETAINED_ATTEMPT_OPTIONS = {
    "campaign matrix-geometry-bind-qualification": "--attempt-dir",
    "campaign matrix-geometry-prepare": "--attempt-dir",
    'campaign matrix-geometry-prove': "--attempt-dir",
    'campaign matrix-geometry-run': "--attempt-dir",
    'campaign matrix-geometry-result': "--attempt-dir",
    'campaign matrix-geometry-conformance': "--attempt-dir",
    'campaign matrix-geometry-qualification': "--attempt-dir",
    'campaign selected-parent-reconstruct': "--attempt-dir",
    'campaign selected-parent-alternate': "--attempt-dir",
    'campaign selected-events-prepare': "--attempt-dir",
    'campaign selected-events-prove': "--attempt-dir",
    'campaign selected-events-run': "--attempt-dir",
    'campaign selected-events-conformance': "--attempt-dir",
    'campaign selected-events-result': "--attempt-dir",
    'campaign matrix-history-allocation': "--attempt-dir",
    'campaign matrix-history-source-config': "--attempt-dir",
    'campaign matrix-history-source-export': "--attempt-dir",
    'campaign matrix-history-import': "--attempt-dir",
    'campaign matrix-history-analyze': "--attempt-dir",
    'campaign matrix-history-result': "--attempt-dir",
    'campaign matrix-transient-analyze': "--attempt-dir",
    'campaign matrix-baseline-analyze': "--attempt-dir",
    'campaign matrix-tangent-config': "--attempt-dir",
    'campaign matrix-tangent-source-export': "--attempt-dir",
    'campaign matrix-tangent-analyze': "--attempt-dir",
    'campaign matrix-analysis-result': "--attempt-dir",
    'campaign preparation-diagnostic-phase-prepare': "--attempt-dir",
    'campaign preparation-diagnostics-prepare': "--attempt-dir",
    'campaign preparation-diagnostics': "--attempt-dir",
    'campaign preparation-diagnostics-result': "--attempt-dir",
    'campaign preparation-result': '--attempt-dir',
    'campaign preparation-allocation-prepare': '--attempt-dir',
    'campaign finite-response-allocation': '--attempt-dir',
    'campaign matrix-source-config': '--attempt-dir',
    'campaign finite-response-packet': '--attempt-dir',
    'campaign finite-response-parent': '--attempt-dir',
    'campaign finite-response-result': '--attempt-dir',
    'campaign rc-challenge-result': '--attempt-dir',
    'campaign preparation-conformance': '--attempt-dir',
    'campaign preparation-exposure-inspect': '--attempt-dir',
    'campaign preparation-input-publish': '--attempt-dir',
    'campaign preparation-selection-prepare': '--attempt-dir',
    'campaign preparation-q-bind': '--attempt-dir',
    'campaign preparation-panel-bind': '--attempt-dir',
    'campaign preparation-panel-export': '--attempt-dir',
    'campaign preparation-author': '--attempt-dir',
    'campaign rc-challenge-author': '--attempt-dir',
    'campaign integration-proof': '--output-dir',
    'campaign finite-response-bind-runtime': '--attempt-dir',
    'campaign finite-response-author': '--attempt-dir',
    'campaign rc-challenge-source-export': '--attempt-dir',
    'campaign matrix-source-export': '--attempt-dir',
    'campaign preparation-source-export': '--attempt-dir',
    'campaign preparation-readiness': '--attempt-dir',
    'campaign preparation-screen': '--attempt-dir',
    'campaign preparation-operands-export': '--attempt-dir',
    'campaign nomination-check': '--output-dir',
    'campaign nomination-export': '--attempt-dir',
    'campaign original-f-check': '--output-dir',
    'campaign original-f-export': '--attempt-dir',
    'campaign battery-native-check': '--output-dir',
    'campaign brian2-native-check': '--output-dir',
    'campaign circuit-author': '--attempt-dir',
    'campaign dependent-response-input-check': '--output-dir',
    'campaign electron-gas-author': '--attempt-dir',
    'campaign electron-gas-reference-check': '--output-dir',
    'campaign finite-response-input-check': '--output-dir',
    'campaign finite-response-native-check': '--output-dir',
    'campaign finite-response-stage-input-check': '--output-dir',
    'campaign glenn-import-check': '--output-dir',
    'campaign grid2op-native-check': '--output-dir',
    'campaign gym-torax-native-check': '--output-dir',
    'campaign material-workflow-input-check': '--output-dir',
    'campaign matrix-response-author': '--attempt-dir',
    'campaign prepared-response-native-check': '--output-dir',
    'campaign propulsion-reference-check': '--output-dir',
    'campaign rc-ladder-native-check': '--output-dir',
    'campaign reaction-response-native-check': '--output-dir',
    'campaign reactor-author': '--attempt-dir',
    'campaign reactor-batch-input-check': '--output-dir',
    'campaign reactor-prepared-input-check': '--output-dir',
    'campaign response-composition-input-check': '--output-dir',
    'campaign response-composition-power': '--output-dir',
    'campaign scale-morphism-reference-check': '--output-dir',
    'campaign synthetic-material-author': '--attempt-dir',
    'campaign torax-native-check': '--output-dir',
    'example reactor-prefix': '--attempt-dir',
    'example rc-information': '--output-dir',
}


COMMAND_METADATA = (
    CommandMetadata("campaign matrix-geometry-bind-qualification", "current paper integration", "authenticated numerical prerequisites; no authority", "writes one fresh bound configuration", "explicit guarded profile", "no", "no authority created", "experiments/matrix-geometry/guide.md", native_software="no native contact at this verb", native_status="exact retained numerical input binding"),
    CommandMetadata("campaign matrix-geometry-prepare", "current paper integration", "explicit numeric allocation; no eligibility", "writes one fresh current configuration", "no", "no", "no authority created", "experiments/matrix-geometry/guide.md", native_software="no native contact at this verb", native_status="complete allocation/resource preparation"),
    CommandMetadata('campaign matrix-geometry-prove', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'no', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-geometry/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-geometry-run', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'explicit native development acquisition and guarded retained outputs', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-geometry/guide.md', native_software='locked base NumPy/SciPy', native_status='explicit non-promotable development execution'),
    CommandMetadata('campaign matrix-geometry-result', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-geometry/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-geometry-conformance', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'explicit native development acquisition and guarded retained outputs', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-geometry/guide.md', native_software='locked base NumPy/SciPy', native_status='explicit non-promotable development execution'),
    CommandMetadata('campaign matrix-geometry-qualification', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'explicit native development acquisition and guarded retained outputs', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-geometry/guide.md', native_software='locked base NumPy/SciPy', native_status='explicit non-promotable development execution'),
    CommandMetadata('campaign selected-parent-reconstruct', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'explicit native development acquisition and guarded retained outputs', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/selected-events/guide.md', native_software='locked base NumPy/SciPy', native_status='explicit non-promotable development execution'),
    CommandMetadata('campaign selected-parent-alternate', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/selected-events/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign selected-events-prepare', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/selected-events/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign selected-events-prove', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/selected-events/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign selected-events-run', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'explicit native development acquisition and guarded retained outputs', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/selected-events/guide.md', native_software='locked base NumPy/SciPy', native_status='explicit non-promotable development execution'),
    CommandMetadata('campaign selected-events-conformance', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'explicit native development acquisition and guarded retained outputs', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/selected-events/guide.md', native_software='locked base NumPy/SciPy', native_status='explicit non-promotable development execution'),
    CommandMetadata('campaign selected-events-result', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/selected-events/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-history-allocation', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'no', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-history-analysis/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-history-source-config', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'no', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-history-analysis/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-history-source-export', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'explicit native development acquisition and guarded retained outputs', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-history-analysis/guide.md', native_software='locked base NumPy/SciPy', native_status='explicit non-promotable development execution'),
    CommandMetadata('campaign matrix-history-import', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-history-analysis/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-history-analyze', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-history-analysis/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-history-result', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-history-analysis/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-transient-analyze', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-transient/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-baseline-analyze', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-transient/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-tangent-config', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'no', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-tangent/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-tangent-source-export', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'explicit native development acquisition and guarded retained outputs', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-tangent/guide.md', native_software='locked base NumPy/SciPy', native_status='explicit non-promotable development execution'),
    CommandMetadata('campaign matrix-tangent-analyze', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-tangent/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign matrix-analysis-result', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'no issued authority created; development or outcome-visible analysis', 'experiments/matrix-transient/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign preparation-diagnostic-phase-prepare', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'actual current issue/execution/reveal grants before protected reads', 'experiments/preparation-diagnostics/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign preparation-diagnostics-prepare', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'actual current issue/execution/reveal grants before protected reads', 'experiments/preparation-diagnostics/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign preparation-diagnostics', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'actual current issue/execution/reveal grants before protected reads', 'experiments/preparation-diagnostics/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata('campaign preparation-diagnostics-result', "current paper integration", "software/development or post-hoc analysis; no inherited scientific qualification", 'read or write explicitly selected inputs/results; no overwrite; optional retained attempt', 'explicit guarded profile', "no; actual observed development source is retained", 'actual current issue/execution/reveal grants before protected reads', 'experiments/preparation-diagnostics/guide.md', native_software='no native contact at this verb', native_status='static proof, typed preparation or authenticated retained analysis'),
    CommandMetadata("campaign original-f-export", "current integration", 'fixed provenance or exposed analysis; no inherited scientific qualification', 'writes explicitly selected current inputs/results; no overwrite', 'no', 'no', 'none', 'experiments/matrix-inputs/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign original-f-check", "current integration", 'fixed provenance or exposed analysis; no inherited scientific qualification', 'read-only authentication; optional attempt diagnostics', 'no', 'no', 'none', 'experiments/matrix-inputs/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign nomination-export", "current integration", 'fixed provenance or exposed analysis; no inherited scientific qualification', 'writes explicitly selected current inputs/results; no overwrite', 'no', 'no', 'none', 'experiments/finite-response-law/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign nomination-check", "current integration", 'fixed provenance or exposed analysis; no inherited scientific qualification', 'read-only authentication; optional attempt diagnostics', 'no', 'no', 'none', 'experiments/finite-response-law/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign preparation-operands-export", "current integration", 'fixed provenance or exposed analysis; no inherited scientific qualification', 'writes explicitly selected current inputs/results; no overwrite', 'explicit guarded profile', 'no; actual observed development source is retained', 'none', 'experiments/matrix-inputs/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign preparation-screen", "current integration", 'fixed provenance or exposed analysis; no inherited scientific qualification', 'writes explicitly selected current inputs/results; no overwrite', 'no', 'no', 'none', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign preparation-readiness", "current integration", 'fixed provenance or exposed analysis; no inherited scientific qualification', 'writes explicitly selected current inputs/results; no overwrite', 'explicit guarded profile', 'no; actual observed development source is retained', 'none', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign preparation-source-export", "current integration", 'current exposed native source', 'explicit native development acquisition and retained source/results; no qualification', 'explicit guarded profile', 'no', 'actual current authority required for protected outcomes/execution; this command creates no grant', 'experiments/matrix-inputs/guide.md', native_software='NumPy 2.4.6; locked base environment', native_status='explicit development acquisition'),
    CommandMetadata("campaign matrix-source-export", "current integration", 'current exposed native source', 'explicit native development acquisition and retained source/results; no qualification', 'explicit guarded profile', 'no', 'actual current authority required for protected outcomes/execution; this command creates no grant', 'experiments/matrix-inputs/guide.md', native_software='NumPy 2.4.6; locked base environment', native_status='explicit development acquisition'),
    CommandMetadata('campaign finite-response-packet', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/finite-response-law/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign finite-response-parent', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/finite-response-law/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign finite-response-result', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/finite-response-law/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign rc-challenge-result', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/rc-challenges/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign preparation-conformance', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/preparation-applicability/guide.md', native_software='base NumPy/SciPy source; explicit bounded native contact', native_status='six bounded software conformance cells; no scientific campaign'),
    CommandMetadata('campaign preparation-exposure-inspect', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign preparation-input-publish', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign preparation-selection-prepare', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign preparation-q-bind', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign preparation-panel-bind', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign preparation-panel-export', 'current integration', 'current inputs or authenticated retained results; software conformance is not qualification', 'writes an explicitly selected new result/input; no overwrite', 'explicit guarded profile', 'no', 'actual current grants required for protected outcomes; creates no authority', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='portable inspection, preparation or authenticated current result access'),
    CommandMetadata('campaign matrix-source-config', 'current integration', 'current source configuration; no scientific eligibility', 'writes one selected new configuration', 'no', 'no', 'no authority created', 'experiments/matrix-inputs/guide.md', native_software='no native contact at this verb', native_status='portable typed source configuration preparation'),
    CommandMetadata('campaign finite-response-allocation', 'current integration', 'explicit numerical proposal; no freshness or authority', 'writes one selected new allocation', 'no', 'no', 'no authority created', 'experiments/finite-response-law/guide.md', native_software='no native contact at this verb', native_status='portable typed allocation preparation'),
    CommandMetadata('campaign preparation-allocation-prepare', 'current integration', 'explicit allocated numerical proposal; no scientific freshness', 'writes one new selected allocation', 'explicit guarded profile', 'no', 'no authority created', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='current ordinary32/64 or constructed8/32 typed allocation preparation'),
    CommandMetadata('campaign preparation-result', 'current integration', 'actual current scientific report; no rerun', 'writes one selected receipt-bound scientific result', 'explicit guarded profile', 'no', 'actual current issue/execution/reveal grants before protected reads', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='exact current ordinary or constructed report readout'),
    CommandMetadata("campaign rc-challenge-source-export", "current integration", 'fixed provenance or exposed analysis; no inherited scientific qualification', 'writes explicitly selected current inputs/results; no overwrite', 'explicit guarded profile', 'no', 'actual current authority required for protected outcomes/execution; this command creates no grant', 'experiments/rc-challenges/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign finite-response-author", "current integration", 'current authoring authority pending', 'writes explicitly selected current inputs/results; no overwrite', 'explicit guarded profile', 'author/proof/runtime binding', 'actual current authority required for protected outcomes/execution; this command creates no grant', 'experiments/finite-response-law/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign finite-response-bind-runtime", "current integration", 'fixed provenance or exposed analysis; no inherited scientific qualification', 'writes explicitly selected current inputs/results; no overwrite', 'explicit guarded profile', 'author/proof/runtime binding', 'actual current authority required for protected outcomes/execution; this command creates no grant', 'experiments/finite-response-law/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign integration-proof", "current integration", 'software provider/graph proof; no scientific execution', 'read-only authentication; optional attempt diagnostics', 'explicit guarded profile', 'author/proof/runtime binding', 'actual current authority required for protected outcomes/execution; this command creates no grant', 'docs/integrations.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign rc-challenge-author", "current integration", 'current authoring authority pending', 'writes explicitly selected current inputs/results; no overwrite', 'explicit guarded profile', 'author/proof/runtime binding', 'actual current authority required for protected outcomes/execution; this command creates no grant', 'experiments/rc-challenges/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata("campaign preparation-author", "current integration", 'current authoring authority pending', 'writes explicitly selected current inputs/results; no overwrite', 'explicit guarded profile', 'author/proof/runtime binding', 'actual current authority required for protected outcomes/execution; this command creates no grant', 'experiments/preparation-applicability/guide.md', native_software='no native contact at this verb', native_status='portable inspection, numerical analysis or no-contact authoring'),
    CommandMetadata(
        "example rc-information", "analytical calculation",
        "common-input RC construction and independent equation check",
        "reads one bounded config; optional --output-dir retains input, report and diagnostics",
        "no", "no", "no scientific authority or sampled qualification",
        "experiments/rc-information/guide.md",
        native_software="Python 3.11, Decimal and mpmath; no native simulator",
        native_status="analytical calculation; no native contact",
    ),
    CommandMetadata("workflow list", "installed", "static workflow inventory; readiness uninspected", "read-only; no input reads, providers or native contact", "no", "no", "no", "experiments/README.md", native_software="no native contact at this verb", native_status="portable inspection or local validation"),
    CommandMetadata("workflow show", "installed", "static workflow commands, roles and stopping points; readiness uninspected", "read-only; no input reads, providers or native contact", "no", "no", "no", "experiments/README.md", native_software="no native contact at this verb", native_status="portable inspection or local validation"),
    CommandMetadata("config validate", "installed", "typed values and consumer byte readiness; no scientific qualification", "reads one bounded declared config; no writes or native contact", "no", "no", "no", "docs/configuration.md", native_software="no native contact at this verb", native_status="portable inspection or local validation"),
    CommandMetadata("config prepare", "installed", "new canonical copy for an editable allowlisted consumer; no authority", "reads a bounded config; writes one explicitly new file; no overwrite or native contact", "no", "no", "no", "docs/configuration.md", native_software="no native contact at this verb", native_status="portable inspection or local validation"),
    CommandMetadata("config schema", "installed", "offline structural editor schema; typed consumers remain semantic authority", "read-only packaged resources; no config reads or native contact", "no", "no", "no", "docs/configuration.md", native_software="no native contact at this verb", native_status="portable inspection or local validation"),
    CommandMetadata(
        "campaign response-composition-power",
        "design diagnostic",
        "fixed-sample response-composition sensitivity",
        'read-only. Computes design probabilities without source, outcome or native contact; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "no",
        "no",
        "none. No cohort, nomination, fitted-package qualification, issue or prospective support",
        "experiments/finite-response-law/guide.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "campaign reactor-batch-input-check",
        "installed",
        "held full-batch reactor source and provider preflight",
        'read-only. Authenticates four upstream members and constructs the registered provider without native contact; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target input config and researcher-held upstream tree",
        "no",
        "none. No candidate, native task, issue or exposed-roster promotion",
        "experiments/reactor-response/guide.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "campaign reactor-prepared-input-check",
        "installed",
        "eight retained reactor response input and binding preflights",
        'read-only. Builds route-specific typed design/native config, selects its binding, checks optional typed upstream identities and reports missing ports; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target route config and held four-member source. Discovery for six routes. Optional upstream binding requires a trusted live target port store",
        "no",
        "none. Exposed retained roster, no candidate, native task or issue",
        "experiments/reactor-response/guide.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "campaign prepared-response-native-check",
        "installed",
        "excluded prepared-response native canary",
        'read-only. Executes one paired hold/action root in two native views; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target development config and CPython 3.11.14/NumPy 2.4.6",
        "no",
        "none. No candidate, issue or matrix-response source qualification",
        "experiments/prepared-response/guide.md",
        native_software="CPython 3.11.14, NumPy 2.4.6. Excluded prepared-root config",
        native_status="bounded prepared native canary. Exposed development only. No candidate or issue",
    ),
    CommandMetadata(
        "campaign matrix-response-author",
        "installed",
        "prepared, information and causal matrix-response candidate authoring",
        'Reads held census, plan and optional fitted bank. Constructs the native source provider and compiles without native contact. With --output-dir, writes strict records and candidate files to a new external directory.; optional --attempt-dir writes a bounded operational attempt separately from scientific custody',
        "target development config, project root, held census, plan, design packet and route bank",
        "no",
        "none. Generated candidate and exposed fitted inputs are nonpromotable",
        "experiments/prepared-response/guide.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign dependent-response-input-check",
        "installed",
        "prepared-response preflight for qualified dependence or calibration parents",
        'read-only. Refuses before parent or outcome read without target custody and separate reveal/analysis authority; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict D or C-P development selection and external parent/authority locators",
        "no",
        "none. Published custody/reveal/analysis grants and qualified parents required to build the provider. No native task or issue",
        "experiments/prepared-response/guide.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "campaign response-composition-input-check",
        "installed",
        "response-composition preflight for an outcome-visible scalar parent",
        'read-only. Refuses before post-hoc scalar read without target custody and separate reveal/analysis authority; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict exposed scalar-parent development selection and external parent/authority locators",
        "no",
        "none. Published custody/reveal/analysis grants and an authenticated target-typed scalar parent required. A negative prepared parent is valid. Selection performs no analysis",
        "experiments/causal-transfer-audit/guide.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "campaign finite-response-input-check",
        "installed",
        "finite-lawhood calibration roster and external assignment preflight",
        'read-only. Checks frozen plan, old-roster collision or assigned root and stream reservation without native binding; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target development input, held plan/exposure census and optional external assignment",
        "no",
        "none. No candidate, native task or issue. Qualified parent custody still required",
        "experiments/finite-response-law/guide.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "campaign finite-response-stage-input-check",
        "installed",
        "finite-lawhood seven-stage typed entry preflight",
        'read-only. Selects the retained stage binding and refuses missing assignment or unresolved parent authority before any task; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target stage config, held plan/exposure and stage-specific external assignment or parent records",
        "no",
        "none. Assigned matrix-response and dependent-parent providers or retained scalar consumers require exact inputs and grants. No task or issue",
        "experiments/finite-response-law/guide.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "campaign finite-response-native-check",
        "installed",
        "excluded finite matrix-response native canary",
        'read-only. Executes one root in two views with paired hold/action futures; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target development config and CPython 3.11.14/NumPy 2.4.6",
        "no",
        "none. No candidate, issue, parent qualification or finite-lawhood verdict",
        "experiments/finite-response-law/guide.md",
        native_software="CPython 3.11.14, NumPy 2.4.6. Excluded finite matrix-response config",
        native_status="bounded finite native canary. Exposed development only. No candidate or issue",
    ),
    CommandMetadata(
        "campaign scale-morphism-reference-check",
        "installed",
        "bounded physical scale-morphism method reference without truth access",
        'read-only. Computes thirty generated cases and exact oracle scores; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target-owned development config and base NumPy/SciPy",
        "no",
        "none. No physical board, candidate, issue or claim promotion",
        "experiments/response-method-reference/guide.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "campaign glenn-import-check",
        "installed",
        "retrospective exact public archive transform, local inspection only",
        'read-only. Previews pinned public selection or verifies held ZIP and burst table; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target selector and researcher-held Zenodo 17163053 ZIP",
        "no",
        "none. No custody qualification, candidate, issue or physical actuation",
        "experiments/laser-archive-inspection/guide.md",
        native_software='exact researcher-held Zenodo 17163053 ZIP for import. None for preview',
        native_status='retrospective local inspection. No custody or candidate',
    ),
    CommandMetadata(
        "campaign propulsion-reference-check",
        "installed",
        "bounded truth-known closure and reliability development reference",
        'read-only. Computes fresh synthetic worlds and nested decision/cycle views; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target-owned propulsion-reliability config and base NumPy",
        "no",
        "none. No physical ICF, candidate or issued campaign",
        "experiments/propulsion-reliability-reference/guide.md",
        native_software='base NumPy and strict truth-known development config',
        native_status='bounded method reference. No physical ICF or candidate',
    ),
    CommandMetadata(
        "campaign material-workflow-wrap-raw",
        "installed",
        "one unqualified material-control native-output envelope",
        "writes a fresh HDF5 wrapper after bounded tar and positive-member presence checks",
        "researcher-supplied raw QE/PH/EPW/Wannier tar and exact material-control profile",
        "no",
        "none. No solver run, material reduction, freeze or issue",
        "experiments/material-control-inputs/guide.md",
        native_software='one researcher-supplied bounded QE/EPW raw tar',
        native_status='writes one unqualified native envelope. No material result',
    ),
    CommandMetadata(
        "campaign material-workflow-input-check",
        "installed",
        "material-control native-input preflight for five controls",
        'read-only. Hashes ten separately supplied HDF5 raw workflow envelopes; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target config and researcher-custodied material-control outputs",
        "no",
        "none. No material reduction, candidate, freeze or issue",
        "experiments/material-control-inputs/guide.md",
        native_software='ten researcher-held material-control raw HDF5 envelopes',
        native_status='read-only input integrity preflight. No material result',
    ),
    CommandMetadata(
        "campaign torax-native-check",
        "installed",
        "paired bounded direct TORAX heat development views",
        'read-only. Executes two native 40 ms heat actions on one preparation; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target config and open-simulators group",
        "no",
        "none. This is not a compiled or issued campaign",
        "experiments/tokamak-heat-response/guide.md",
        native_software='TORAX 1.4.2. Strict synthetic heat input',
        native_status='paired direct native development views. No candidate or issue',
    ),
    CommandMetadata(
        "campaign gym-torax-native-check",
        "installed",
        "paired bounded Gym--TORAX development episodes",
        'read-only. Executes two native 120-request episodes on one preparation; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target config, clean target checkout and open-simulators group",
        "yes, Gym--TORAX 1.1.1 and TORAX 1.4.2",
        "none. This is not a compiled or issued campaign",
        "experiments/tokamak-control-response/guide.md",
        native_software='Gym--TORAX 1.1.1, TORAX 1.4.2 and target source checkout',
        native_status='paired native development episodes. No candidate or issue',
    ),
    CommandMetadata(
        "campaign grid2op-native-check",
        "installed",
        "one held chronic with paired development branches",
        'read-only. Hashes held source and executes bounded native steps; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict selection, operator-held wheels and offline dataset, grid2op-held group",
        "yes, Grid2Op 1.12.5 and LightSim2Grid 0.13.1",
        "none. This is not a compiled or issued campaign",
        "experiments/grid-response-inputs/guide.md",
        native_software='Grid2Op 1.12.5, LightSim2Grid 0.13.1 and held offline source',
        native_status='one held-chronic native development check. No candidate or issue',
    ),
    CommandMetadata(
        "campaign battery-native-check",
        "installed",
        "three distinct bounded PyBaMM development contracts",
        'read-only. Executes five native development preparations across battery electrothermal/battery exact restart/battery reduced observation; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target-owned or researcher-supplied battery config and open-simulators group",
        "yes, PyBaMM 26.6.2.0",
        "none. This is not a compiled or issued campaign",
        "experiments/battery-response-and-restart/guide.md",
        native_software='PyBaMM 26.6.2.0. Strict battery development config',
        native_status='three bounded native contracts. No candidate or issue',
    ),
    CommandMetadata(
        "campaign electron-gas-reference-check",
        "installed",
        "one bounded analytic transverse-response development unit",
        'read-only. Computes SI finite-q and slab reference transforms; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target-owned or researcher-supplied uniform electron gas quick-start config",
        "no",
        "none. This is not a compiled or issued campaign",
        "experiments/electron-gas-response/guide.md",
        native_software='Python 3.11 and SciPy. Strict uniform electron gas analytic config',
        native_status='bounded analytic development check. No candidate or issue',
    ),
    CommandMetadata(
        "campaign reaction-response-native-check",
        "installed",
        "strict Cantera or FiPy native development panel",
        'read-only. Executes one bounded native complete unit; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "target-owned Cantera or FiPy quick-start config and pinned optional group",
        "yes, Cantera or FiPy",
        "none. This is not a compiled or issued campaign",
        "experiments/reactor-flow-response/guide.md, experiments/reaction-diffusion-response/guide.md",
        native_software='Cantera 3.2.0 or FiPy 4.0.3. Strict native config',
        native_status='bounded local native panel. No candidate or issue',
    ),
    CommandMetadata(
        "campaign brian2-native-check",
        "installed",
        "separately pinned native LIF contract check",
        'read-only. Executes two bounded, reset Brian2 native arms; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target-owned or researcher-supplied config and native Python",
        "no",
        "none. This is not a compiled or issued campaign",
        "experiments/neuron-current-response/guide.md",
        native_software='Separate CPython 3.11.14, Brian2 2.9.0 and NumPy 1.26.4',
        native_status='bounded local LIF check. No candidate or issue',
    ),
    CommandMetadata(
        "campaign rc-ladder-native-check",
        "installed",
        "local numerical RC contract check",
        'read-only. Executes a bounded native numerical calculation; optional --output-dir writes a bounded operational attempt separately from scientific custody',
        "strict target-owned or researcher-supplied model config",
        "no",
        "none. This is not a compiled or issued campaign",
        "experiments/rc-ladder-response/guide.md",
        native_software='Python 3.11, NumPy and SciPy. Strict RC model config',
        native_status='bounded local numerical check. No candidate or issue',
    ),
    CommandMetadata(
        "campaign reactor-author",
        "installed",
        "fresh authoring with authority pending",
        'writes strict records and pure plan projections under --output-dir; optional --attempt-dir writes a bounded operational attempt separately from scientific custody',
        "guarded artifact namespace. Packaged public source only",
        "clean target commit required",
        "none. Source and native tasks are not contacted",
        "docs/fresh-experiment.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign circuit-author",
        "installed",
        "strict resistor-capacitor numerical authoring and projection before issue",
        'writes strict records under --output-dir. No native task runs; optional --attempt-dir writes a bounded operational attempt separately from scientific custody',
        "guarded artifact namespace. Strict local RC study config",
        "clean target commit required",
        "none. Study bytes are decoded without simulator contact",
        "experiments/rc-ladder-response/guide.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign electron-gas-author",
        "installed",
        "strict electron-gas analytic-development authoring and projection before issue",
        'writes strict records under --output-dir. No native task runs; optional --attempt-dir writes a bounded operational attempt separately from scientific custody',
        "guarded artifact namespace. Strict local uniform electron gas config",
        "clean target commit required",
        "none. Synthetic source is not contacted",
        "experiments/electron-gas-response/guide.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign synthetic-material-author",
        "installed",
        "strict lattice-pairing method authoring and projection before issue",
        'writes strict records under --output-dir. No method task runs; optional --attempt-dir writes a bounded operational attempt separately from scientific custody',
        "guarded artifact namespace. Strict local A3 R2 fixture config",
        "clean target commit required",
        "none. Synthetic method suite is not contacted",
        "experiments/lattice-pairing-method/guide.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign reactor-preissue-proof",
        "installed",
        "no-contact full production-route proof",
        "writes and replays full control records in guarded external custody",
        "guarded artifact namespace and exact authoring directory",
        "clean target commit required",
        "none. Output locators, runners and authority inputs are resolved",
        "docs/fresh-experiment.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "source preview",
        "installed",
        "bounded public source selection",
        "read-only. No source contact",
        "none",
        "no",
        "none",
        "docs/sources.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "source acquire",
        "installed",
        "public source acquisition",
        "bounded network reads and guarded external custody",
        "public endpoint and explicit storage profile",
        "clean target commit required",
        "exact separate source-acquisition and custody-publication authority",
        "docs/sources.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "source recover",
        "installed",
        "same-attempt source recovery",
        "bounded network reads if incomplete. Verifies immutable receipt",
        "public endpoint and explicit storage profile",
        "clean target commit required",
        "same exact source and custody authority",
        "docs/sources.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "source design-input",
        "installed",
        "prospective source input binding",
        "reads and verifies external receipt and actual custodied bytes",
        "explicit storage profile",
        "no new source identity claim",
        "none. Issue remains separate",
        "docs/sources.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "example reactor-prefix",
        "demonstration",
        "unqualified native reactor measurement",
        'writes typed panel and report under --output-dir; optional --attempt-dir writes a bounded operational attempt separately from scientific custody',
        "no",
        "no",
        "no scientific authority or law qualification",
        "experiments/reactor-response/guide.md",
        native_software='Python 3.11.14, NumPy 2.4.6, packaged public plant',
        native_status='portable native demonstration. No qualification',
    ),
    CommandMetadata(
        "campaign bind-elapsed-budget",
        "installed",
        "cumulative elapsed-time package binding",
        "read-only unless optional local emission is requested",
        "exact supplied issued records",
        "source identity is checked at later issue/execution gates",
        "exact execution-package authorization and elapsed-time contract",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. Source identity and external inputs gated',
    ),
    CommandMetadata(
        "doctor",
        "installed",
        "diagnostic-only",
        "read-only",
        "inspect only",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "system validate",
        "installed",
        "authoring validation",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "system inspect",
        "installed",
        "catalog metadata/pointer",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign validate",
        "installed",
        "authoring validation",
        "read-only",
        "authority-store read for package roots",
        "no",
        "bound authorization replay for package roots",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='draft portable. Package authority replay gated',
    ),
    CommandMetadata(
        "campaign compile-plan",
        "installed",
        "immutable DAG compilation",
        "read-only",
        "authority-store read",
        "no",
        "bound authorization checked",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. Source identity and external inputs gated',
    ),
    CommandMetadata(
        "campaign compile-study",
        "installed",
        "nonauthoritative candidate compilation",
        "read-only unless optional compact local emission is requested",
        "no",
        "no",
        "none. Expected later gates are reported, not granted",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. Source identity and external inputs gated',
    ),
    CommandMetadata(
        "campaign compile-candidate",
        "installed",
        "extension-aware nonauthoritative candidate compilation",
        "read-only unless optional compact local emission is requested",
        "no",
        "no",
        "none. Later issue and execution gates remain open",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. Source identity and external inputs gated',
    ),
    CommandMetadata(
        "campaign check-readiness",
        "installed",
        "exact nonauthorizing future-topology readiness",
        "read-only",
        "exact supplied control records only. No source contact",
        "no",
        "none. Issue, approval, execution and reveal remain separate",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign source-profile-compile",
        "installed",
        "outcome-blind source-readiness compilation",
        "read-only unless optional compact local emission is requested",
        "no source bytes. Exact supplied control records only",
        "no",
        "none. A supplied dataset request is replayed but authority is never created",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign linked-profile-compile",
        "installed",
        "four-package profile and executable-binding join",
        "read-only unless optional compact local emission is requested",
        "no",
        "no",
        "none. Reports condition and authority stops without creating descendants",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign assemble-package",
        "installed",
        "current issued-package assembly",
        "read-only unless optional compact local no-replace emission is requested",
        "exact supplied issued/resource/JIT records only",
        "no",
        "exact scientific approval and execution authority replay required",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. Source identity and external inputs gated',
    ),
    CommandMetadata(
        "campaign compile-bundle",
        "installed",
        "multi-world candidate and deterministic fan-in compilation",
        "read-only unless optional compact local emission is requested",
        "no",
        "no",
        "none. Every child and parent gate remains open",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign issue",
        "installed",
        "outcome-blind issue/freeze",
        "writes atomic external custody publication after confirmation. Preview is read-only",
        "custody/publication authority required",
        "no",
        "accountable proposer and exact source closure checked. Grants no later authority",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. Source identity and external inputs gated',
    ),
    CommandMetadata(
        "campaign issue-extensions",
        "installed",
        "extension-aware outcome-blind child issue",
        "writes atomic external extension custody publication after confirmation",
        "custody/publication authority required",
        "yes",
        "accountable proposer, clean source and exact extension authority checked",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. Source identity and external inputs gated',
    ),
    CommandMetadata(
        "campaign issue-bundle",
        "installed",
        "outcome-blind three-child parent issue",
        "writes one immutable parent manifest and receipt after confirmation",
        "parent custody/publication authority required",
        "yes",
        "replays three child issues. Grants no execution or reveal authority",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. Source identity and external inputs gated',
    ),
    CommandMetadata(
        "campaign transition-bundle",
        "installed",
        "one ordered parent reveal or terminal child-result bind",
        "read-only transition computation over immutable inputs",
        "trusted authority-store read for reveal. Child result path for bind",
        "no",
        "exact domain reveal authority required only at its transition",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign bundle-status",
        "installed",
        "multi-world parent barrier status",
        "read-only",
        "no",
        "no",
        "no outcome payload read or reveal",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign close-bundle",
        "installed",
        "terminal non-pooling three-world adjudication",
        "read-only deterministic closeout computation",
        "reads exact revealed result records",
        "no",
        "requires a terminal authorized reveal prefix",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign run",
        "installed",
        "receipt-first execution",
        "external artifacts and local operational projection",
        "required",
        "required",
        "scientific and execution authority checked. Evaluator plans also require exact reveal authority",
        "docs/cli.md",
        native_software='selected provider, its native stack and executor enforcement',
        native_status='installed. Execution gated by source, inputs and authority',
    ),
    CommandMetadata(
        "campaign resume",
        "installed",
        "receipt reconciliation",
        "external artifacts and local operational projection",
        "required",
        "required",
        "scientific and execution authority checked. Evaluator plans also require exact reveal authority",
        "docs/cli.md",
        native_software='selected provider, its native stack and executor enforcement',
        native_status='installed. Execution gated by source, inputs and authority',
    ),
    CommandMetadata(
        "campaign status",
        "installed",
        "operational status",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign explore-detect",
        "installed",
        "outcome-visible portfolio",
        "read-only",
        "no",
        "no",
        "none",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign explore-propose",
        "installed",
        "complete analysis family",
        "read-only",
        "no",
        "no",
        "none",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign explore-compile",
        "installed",
        "non-promotable exploration DAG",
        "read-only",
        "no",
        "no",
        "forbidden in worker registry",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign explore-run",
        "installed",
        'input-only non-promotable wave. DualLoopPackage fixture execution is blocked',
        "external artifacts and local operational projection after confirmation",
        "required",
        "required",
        "read-only exploration. Enforced no-network profile required",
        "docs/cli.md",
        native_software='selected provider, its native stack and executor enforcement',
        native_status='installed. Execution gated by source, inputs and authority',
    ),
    CommandMetadata(
        "campaign explore-synthesize",
        "installed",
        "competing hypotheses",
        "read-only",
        "no",
        "no",
        "none",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign nominate-next",
        "installed",
        "fresh-evidence nomination",
        "read-only",
        "no",
        "no",
        "advisory only",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign propose-next",
        "installed",
        "authority-pending experiment",
        "read-only",
        "no",
        "no",
        "authority required",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "campaign authorize-nonactuating",
        "installed containment",
        "outcome-blind approval preview",
        "read-only. Always AUTHORITY_REQUIRED until complete envelope exists",
        "no",
        "no",
        "no authorization record",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "capability list",
        "installed",
        "bounded static capability registrations",
        "read-only",
        "no",
        "no",
        "no provider loading or execution",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "capability show",
        "installed",
        "exact static capability registration",
        "read-only",
        "no",
        "no",
        "no provider loading or execution",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "authority inspect",
        "installed",
        "authority metadata",
        "read-only",
        "no",
        "no",
        "no outcome access",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "law inspect",
        "installed",
        "law metadata",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "atlas inspect",
        "installed",
        "atlas metadata",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "atlas gaps",
        "installed",
        "atlas support-gap metadata",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "admission explain",
        "installed",
        "admission metadata",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "control inspect",
        "installed",
        "controller identity metadata",
        "read-only",
        "no",
        "no",
        "no execution",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "control validate",
        "installed",
        "controller identity validation",
        "read-only",
        "no",
        "no",
        "no execution",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "catalog query",
        "installed",
        "cursor-paginated metadata/pointers. Capped match count",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "dataset validate",
        "installed",
        "dataset manifest validation",
        "read-only",
        "manifest input only",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='portable inspection or local validation',
    ),
    CommandMetadata(
        "dataset preview",
        "installed",
        "outcome-blind dataset operation preflight",
        "read-only",
        "registered scopes inspected. Scientific bytes unopened",
        "required",
        "exact durable dataset-operation authorization",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "dataset rebuild",
        "installed",
        "authorized unified scientific-plus-dataset projection install",
        "writes local SQLite and external projection receipt",
        "exact registered projection scope and receipt scope",
        "required plus --yes confirmation",
        "dedicated durable dataset-projection-rebuild authorization",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "dataset register",
        "installed",
        "authorized verification and durable registration of exact held bytes",
        "reads exact held source. Writes external registration control batch",
        "exact registered source and control scopes",
        "required plus --yes confirmation",
        "exact durable dataset-registration authorization",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "dataset list",
        "installed",
        "authenticated dataset metadata",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "dataset show",
        "installed",
        "authenticated dataset identity metadata",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "catalog rebuild",
        "installed",
        "projection reconstruction",
        "local SQLite replacement",
        "projection read",
        "no",
        "dedicated durable authorization for unified dataset projections",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "db init",
        "installed",
        "projection schema",
        "local SQLite create/migrate",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "db check",
        "installed",
        "projection integrity",
        "read-only",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
    CommandMetadata(
        "db compact",
        "installed",
        "projection maintenance",
        "local SQLite incremental vacuum",
        "no",
        "no",
        "no",
        "docs/cli.md",
        native_software='no native contact at this verb',
        native_status='installed. External inputs or store state may refuse',
    ),
)


@dataclass(frozen=True, slots=True)
class InvocationContract:
    """Exact invocation prerequisites and result convention. No implicit fallback."""

    project: str
    storage: str
    output: str
    errors: str


# Every installed leaf must appear exactly once. Adding a command without its
# invocation contract is a generator/test failure, never a guessed store requirement.
_INVOCATION_GROUPS = (
    (InvocationContract("target checkout", "profile", "JSON report. No --format", "invalid-2"), ("campaign matrix-geometry-bind-qualification",)),
    (InvocationContract("target checkout", "none", "JSON report. No --format", "invalid-2"), ("campaign matrix-geometry-prepare",)),
    (InvocationContract('none', 'none', "JSON report. No --format", "invalid-2"), ('campaign matrix-geometry-prove', 'campaign matrix-history-allocation', 'campaign matrix-tangent-config')),
    (InvocationContract('target checkout', 'none', "JSON report. No --format", "invalid-2"), ('campaign matrix-history-source-config',)),
    (InvocationContract('target checkout', 'profile', "JSON report. No --format", "invalid-2"), ('campaign matrix-analysis-result', 'campaign matrix-baseline-analyze', 'campaign matrix-geometry-conformance', 'campaign matrix-geometry-qualification', 'campaign matrix-geometry-result', 'campaign matrix-geometry-run', 'campaign matrix-history-analyze', 'campaign matrix-history-import', 'campaign matrix-history-result', 'campaign matrix-history-source-export', 'campaign matrix-tangent-analyze', 'campaign matrix-tangent-source-export', 'campaign matrix-transient-analyze', 'campaign preparation-diagnostic-phase-prepare', 'campaign preparation-diagnostics', 'campaign preparation-diagnostics-prepare', 'campaign preparation-diagnostics-result', 'campaign selected-events-conformance', 'campaign selected-events-prepare', 'campaign selected-events-prove', 'campaign selected-events-result', 'campaign selected-events-run', 'campaign selected-parent-alternate', 'campaign selected-parent-reconstruct')),
    (
        InvocationContract("none", "none", "Deterministic JSON report. No --format", "invalid-2"),
        ('campaign finite-response-allocation', 'campaign matrix-source-config', 'campaign original-f-export', 'campaign original-f-check', 'campaign nomination-export', 'campaign nomination-check', 'campaign preparation-operands-export', 'campaign preparation-screen', 'campaign preparation-readiness'),
    ),
    (
        InvocationContract("--project-root", "--operator-profile", "Deterministic JSON report. No --format", "invalid-2"),
        ('campaign preparation-result', 'campaign preparation-allocation-prepare', 'campaign finite-response-packet', 'campaign finite-response-parent', 'campaign finite-response-result', 'campaign rc-challenge-result', 'campaign preparation-conformance', 'campaign preparation-exposure-inspect', 'campaign preparation-input-publish', 'campaign preparation-selection-prepare', 'campaign preparation-q-bind', 'campaign preparation-panel-bind', 'campaign preparation-panel-export', 'campaign preparation-source-export', 'campaign matrix-source-export', 'campaign rc-challenge-source-export', 'campaign finite-response-author', 'campaign finite-response-bind-runtime', 'campaign integration-proof', 'campaign rc-challenge-author', 'campaign preparation-author'),
    ),
    (
        InvocationContract("none", "none", "Canonical JSON report. No --format", "invalid-2"),
        ("example rc-information",),
    ),
    (
        InvocationContract("none", "none", "Static workflow text/JSON. --format text/json", "invalid-2"),
        ("workflow list", "workflow show"),
    ),
    (
        InvocationContract("none", "none", "Configuration readiness/refusal text/JSON. --format text/json", "invalid-2"),
        ("config validate", "config prepare"),
    ),
    (
        InvocationContract("none", "none", "Packaged JSON Schema. No --format", "invalid-2"),
        ("config schema",),
    ),
    (
        InvocationContract(
            "target checkout", "profile", "ApiResult. --format text/json", "api"
        ),
        (
            "admission explain",
            "atlas gaps",
            "atlas inspect",
            "authority inspect",
            "campaign authorize-nonactuating",
            "campaign compile-bundle",
            "campaign close-bundle",
            "campaign issue-bundle",
            "campaign bundle-status",
            "campaign transition-bundle",
            "campaign compile-study",
            "campaign compile-candidate",
            "campaign compile-plan",
            "campaign explore-compile",
            "campaign explore-detect",
            "campaign explore-propose",
            "campaign explore-run",
            "campaign explore-synthesize",
            "campaign issue",
            "campaign issue-extensions",
            "campaign linked-profile-compile",
            "campaign nominate-next",
            "campaign assemble-package",
            "campaign bind-elapsed-budget",
            "campaign check-readiness",
            "campaign propose-next",
            "campaign resume",
            "campaign run",
            "campaign source-profile-compile",
            "campaign status",
            "catalog query",
            "catalog rebuild",
            "control inspect",
            "control validate",
            "dataset list",
            "dataset preview",
            "dataset rebuild",
            "dataset register",
            "dataset show",
            "db check",
            "db compact",
            "db init",
            "law inspect",
            "system inspect",
        ),
    ),
    (
        InvocationContract(
            "none",
            "none. Supplied profile is validated",
            "ApiResult. --format text/json",
            "api",
        ),
        (
            "capability list",
            "capability show",
            "dataset validate",
            "system validate",
        ),
    ),
    (
        InvocationContract(
            "none. Optional project inspection",
            "optional profile for storage diagnosis",
            "ApiResult. --format text/json",
            "api",
        ),
        ("doctor",),
    ),
    (
        InvocationContract(
            "draft: none. Package: target checkout",
            "draft: none. Package: profile",
            "ApiResult. --format text/json",
            "api",
        ),
        ("campaign validate",),
    ),
    (
        InvocationContract("none", "none", "JSON report. No --format", "refusal-3"),
        (
            "campaign material-workflow-input-check",
            "campaign material-workflow-wrap-raw",
            "campaign brian2-native-check",
            "campaign finite-response-input-check",
            "campaign finite-response-native-check",
            "campaign prepared-response-native-check",
            "campaign electron-gas-reference-check",
            "campaign glenn-import-check",
            "campaign grid2op-native-check",
            "campaign scale-morphism-reference-check",
            "campaign reaction-response-native-check",
            "campaign battery-native-check",
            "campaign reactor-batch-input-check",
            "campaign propulsion-reference-check",
            "campaign torax-native-check",
        ),
    ),
    (
        InvocationContract(
            "target checkout", "none", "JSON report. No --format", "refusal-3"
        ),
        (
            "campaign matrix-response-author",
            "campaign gym-torax-native-check",
        ),
    ),
    (
        InvocationContract(
            "none for preflight. Target checkout for trusted parents or authoring",
            "profile for authenticated parent reads",
            "JSON report. No --format",
            "refusal-3",
        ),
        (
            "campaign dependent-response-input-check",
            "campaign finite-response-stage-input-check",
            "campaign response-composition-input-check",
        ),
    ),
    (
        InvocationContract(
            "none for preflight. Target checkout for trusted upstream ports",
            "profile for authenticated upstream ports",
            "JSON report. No --format",
            "refusal-3",
        ),
        ("campaign reactor-prepared-input-check",),
    ),
    (
        InvocationContract(
            "target checkout", "profile", "JSON report. No --format", "refusal-5"
        ),
        (
            "campaign synthetic-material-author",
            "campaign electron-gas-author",
            "campaign reactor-author",
            "campaign reactor-preissue-proof",
            "campaign circuit-author",
        ),
    ),
    (
        InvocationContract("none", "none", "JSON report. No --format", "invalid-2"),
        (
            "campaign rc-ladder-native-check",
            "campaign response-composition-power",
        ),
    ),
    (
        InvocationContract(
            "none",
            "none. Supplied profile is validated",
            "JSON report. No --format",
            "invalid-2",
        ),
        ("source preview",),
    ),
    (
        InvocationContract(
            "target checkout", "profile", "Canonical JSON record. No --format", "source"
        ),
        (
            "source acquire",
            "source recover",
        ),
    ),
    (
        InvocationContract(
            "target checkout",
            "profile",
            "Canonical JSON record. No --format",
            "refusal-5",
        ),
        ("source design-input",),
    ),
    (
        InvocationContract(
            "none", "none", "Text summary and files. No --format", "example-1"
        ),
        ("example reactor-prefix",),
    ),
)


def invocation_contracts() -> dict[str, InvocationContract]:
    result: dict[str, InvocationContract] = {}
    for contract, commands in _INVOCATION_GROUPS:
        for command in commands:
            if command in result:
                raise ValueError(f"duplicate invocation contract: {command}")
            result[command] = contract
    expected = {value.command for value in COMMAND_METADATA}
    if set(result) != expected:
        raise ValueError(
            "CLI invocation contracts differ from command metadata: "
            f"missing={sorted(expected - set(result))}; stale={sorted(set(result) - expected)}"
        )
    return result
